image: archlinux:base-devel-20230430.0.146624

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pacman-key --init
  - pacman -Syu --noconfirm --noprogressbar
  - pacman -S --noconfirm --noprogressbar python python-virtualenv libglvnd texlive-bin
  - python -m venv venv
  - source venv/bin/activate
  - pip install build setuptools wheel tox

build:
  stage: build
  script:
    - python -m build
  artifacts:
    paths:
      - dist

install_test:
  stage: test
  script:
    - pip install dist/autoinvoice-1.3.0-py3-none-any.whl
    - mkdir void && cd void && python -m autoinvoice --help
    - pip uninstall -y autoinvoice

unittests-arch:
  stage: test
  script:
    - tox run -e local

unittest-fedora:
  stage: test
  image: fedora:37
  before_script:
    - dnf -y check-update && dnf -y upgrade
    - dnf -y install python3.7
    - python3.7 -m ensurepip --user --altinstall
    - python3.7 -m pip install --user tox
    - dnf -y install python3.8
    - python3.8 -m ensurepip --user --altinstall
    - python3.8 -m pip install --user tox
    - dnf -y install python3.9
    - python3.9 -m ensurepip --user --altinstall
    - python3.9 -m pip install --user tox
    - dnf -y install python3.10
    - python3.10 -m ensurepip --user --altinstall
    - python3.10 -m pip install --user tox
    - dnf -y install libglvnd-glx texlive-latex python-tox
  script:
    - python3.7 -m tox run

unittest-debian:
  image: debian:11-slim
  before_script:
    - apt-get update -y && apt-get upgrade -y
    - apt-get install -y python3-pip libglvnd0 texlive-latex-base
    - python3 -m pip install tox
  script:
    - python3 -m tox run -e local
