image: archlinux:base-devel-20241208.0.286830

variables:
  DOCKER_REGISTRY: "localhost:5555"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

unittest-arch:
  stage: test
  image: localhost:5555/archlinux_autoinvoice:latest
  script:
    - tox run

pip_install_test:
  stage: test
  image: localhost:5555/archlinux_autoinvoice:latest
  script:
    - python3 -m build --wheel
    - pip install --break-system-packages dist/autoinvoice-1.3.2-py3-none-any.whl
    - python -m autoinvoice --help
    - pip uninstall -y --break-system-packages autoinvoice
  dependencies:
    - unittest-arch

pipx_install_test:
  stage: test
  image: localhost:5555/archlinux_autoinvoice:latest
  script:
    - export PATH="${PATH}:/root/.local/bin"
    - python3 -m build --wheel
    - pipx install dist/autoinvoice-1.3.2-py3-none-any.whl
    - autoinvoice --help
    - pipx uninstall autoinvoice
  dependencies:
    - unittest-arch

unittest-fedora:
  stage: test
  image: localhost:5555/fedora41_autoinvoice:latest
  allow_failure: true
  script:
    - python3 -m tox run
    - python3 -m build --wheel

unittest-debian:
  stage: test
  image: localhost:5555/debian_autoinvoice:latest
  script:
    - python3 -m tox run
    - python3 -m build --wheel

