image: archlinux:base-devel-20240101.0.204074

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pacman-key --init
  - pacman -Syu --noconfirm --noprogressbar
  - pacman -S --noconfirm --noprogressbar python python-virtualenv libglvnd texlive-bin
  - python -m venv venv
  - source venv/bin/activate
  - pip install build setuptools wheel tox

build:
  stage: build
  script:
    - python -m build
  artifacts:
    paths:
      - dist
    expire_in: 1 week

install_test:
  stage: test
  script:
    - pip install dist/autoinvoice-1.3.0-py3-none-any.whl
    - mkdir void && cd void && python -m autoinvoice --help
    - pip uninstall -y autoinvoice
  dependencies:
    - build

unittests-arch:
  stage: test
  script:
    - python -m tox run
  dependencies:
    - build

unittest-fedora:
  stage: test
  image: fedora:40
  allow_failure: true
  before_script:
    - dnf -y check-update && dnf -y upgrade
    - dnf -y install python3.12
    - python3.12 -m ensurepip --user --altinstall
    - python3.12 -m pip install --user tox
    - dnf -y install libglvnd-glx texlive-latex python-tox
  script:
    - python3 -m tox run
  dependencies:
    - build

unittest-debian:
  stage: test
  image: debian:12-slim
  before_script:
    - apt-get update -y && apt-get upgrade -y
    - apt-get install -y python3-pip libglvnd0 texlive-latex-base tox
  script:
    - python3 -m tox run
  dependencies:
    - build
