FROM debian:12.8-slim

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
      libglvnd0 \
      python3-build \
      python3-pip \
      texlive-latex-base \
      tox 
